version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iso_back_container
    ports:
      - "8020:8020"
    volumes:
      - .:/iso_back
    command: python manage.py runserver 0.0.0.0:8020
    networks:
      - mysql-network


networks:
  mysql-network:
    external:
      name: mysql-network
