# Generated by Django 4.1 on 2022-11-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'ordering': ['id'], 'verbose_name': 'администратора', 'verbose_name_plural': 'Администраторы'},
        ),
        migrations.AddField(
            model_name='admin',
            name='tg_id',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
