# Generated by Django 4.1 on 2022-11-09 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_admin_options_admin_tg_id_alter_admin_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='violation',
            old_name='response_admin_id',
            new_name='response_admin',
        ),
    ]
