# Generated by Django 4.1 on 2022-11-29 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_response_admin_id_violation_response_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='is_no_violation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='violation',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.process'),
        ),
    ]
