# Generated by Django 4.1 on 2022-11-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_violation_is_no_violation_alter_violation_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='photo',
            field=models.FileField(null=True, upload_to='uploads/photo/'),
        ),
    ]
